"""
Model Performance Page - Shows genuine held-out prediction accuracy and metrics

This page reads pre-computed evaluation results from models/performance_metrics.json
and models/performance_test_predictions.csv, generated by notebooks/Advanced/FINALMODELS.ipynb.

Those files come from a Random Forest trained ONLY on the first 80% of matches
(by date) and evaluated on the remaining 20%, which the model never saw during
training or calibration. This avoids the data leakage in an earlier version of
this page, which re-scored the production model (trained on 100% of the data)
against a "test" slice it had already been trained on.
"""

import json
from pathlib import Path

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

OUTCOME_LABELS = {0: "Draw", 1: "Away Win", 2: "Home Win"}


@st.cache_data
def load_performance_data():
    """Load cached held-out evaluation metrics and per-match predictions"""
    base_dir = Path(__file__).resolve().parents[2]
    models_dir = base_dir / "models"

    metrics_path = models_dir / "performance_metrics.json"
    predictions_path = models_dir / "performance_test_predictions.csv"

    if not metrics_path.exists() or not predictions_path.exists():
        return None, None

    with open(metrics_path) as f:
        metrics = json.load(f)

    predictions = pd.read_csv(predictions_path)
    predictions["date"] = pd.to_datetime(predictions["date"])

    return metrics, predictions


def show():
    """Display the model performance page"""
    st.markdown('<div class="sub-header">Model Performance & Accuracy</div>', unsafe_allow_html=True)

    metrics, predictions = load_performance_data()

    if metrics is None:
        st.error(
            "Performance metrics not found. Run the evaluation cell in "
            "`notebooks/Advanced/FINALMODELS.ipynb` to generate "
            "`models/performance_metrics.json` and `models/performance_test_predictions.csv`."
        )
        return

    meta = metrics["_meta"]
    rf_metrics = metrics["random_forest"]

    st.success("Showing Random Forest performance on a genuinely held-out test set")

    with st.expander("About this evaluation"):
        st.markdown(f"""
        - **Method:** Trained on the first {meta['train_size']} matches (by date), evaluated on the
          remaining {meta['test_size']} matches (**{meta['test_start_date']}** to **{meta['test_end_date']}**),
          which the model never saw during training or probability calibration.
        - **Total matches:** {meta['total_matches']}
        - **Result encoding:** `0 = Draw`, `1 = Away Win`, `2 = Home Win`
        - **Note:** These numbers are lower than an earlier, buggy version of this page reported.
          That version scored the production model (trained on 100% of the data) against a slice it
          had already been trained on, which inflated the accuracy. These figures reflect genuine
          out-of-sample performance.
        """)

    st.markdown("---")
    st.subheader("Overall Performance Metrics (held-out test set)")

    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Accuracy", f"{rf_metrics['accuracy']:.1%}", help="Percentage of correct predictions")
    with col2:
        st.metric("Precision", f"{rf_metrics['precision']:.1%}", help="How many predicted outcomes were correct")
    with col3:
        st.metric("Recall", f"{rf_metrics['recall']:.1%}", help="How many actual outcomes were predicted")
    with col4:
        st.metric("F1-Score", f"{rf_metrics['f1_score']:.1%}", help="Harmonic mean of precision and recall")

    home_win_baseline = predictions["actual"].eq(2).mean()
    st.caption(
        f"Baseline for comparison: always predicting Home Win would score "
        f"{home_win_baseline:.1%} accuracy on this same test set."
    )

    st.markdown("---")
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Confusion Matrix")
        conf_matrix = rf_metrics["confusion_matrix"]
        labels = ["Draw", "Away", "Home"]

        fig = go.Figure(data=go.Heatmap(
            z=conf_matrix[::-1],
            x=labels,
            y=labels[::-1],
            text=conf_matrix[::-1],
            texttemplate="%{text}",
            textfont={"size": 16},
            colorscale="Blues",
            showscale=True,
        ))
        fig.update_layout(
            title="Predicted vs Actual Results",
            xaxis_title="Predicted",
            yaxis_title="Actual",
            height=400,
        )
        st.plotly_chart(fig, use_container_width=True)
        st.caption("Diagonal values show correct predictions. Off-diagonal values show errors.")

    with col2:
        st.subheader("Prediction Accuracy by Outcome")
        accuracies = []
        for outcome in [0, 1, 2]:
            mask = predictions["actual"] == outcome
            if mask.sum() > 0:
                acc = (predictions.loc[mask, "predicted"] == outcome).mean()
                accuracies.append({"Outcome": OUTCOME_LABELS[outcome], "Accuracy": acc * 100, "Count": int(mask.sum())})

        if accuracies:
            acc_df = pd.DataFrame(accuracies)
            fig = px.bar(
                acc_df, x="Outcome", y="Accuracy", text="Accuracy", color="Outcome",
                color_discrete_map={"Draw": "#ff7f0e", "Away Win": "#d62728", "Home Win": "#2ca02c"},
            )
            fig.update_traces(texttemplate="%{text:.1f}%", textposition="outside")
            fig.update_layout(yaxis_range=[0, 110], yaxis_title="Accuracy (%)", showlegend=False, height=400)
            st.plotly_chart(fig, use_container_width=True)

            counts_text = ", ".join(f"{row['Outcome']} ({row['Count']})" for row in accuracies)
            st.caption(f"Test set distribution: {counts_text}")

    st.markdown("---")
    st.subheader("Predictions vs Actual Results")

    comparison = predictions.copy()
    comparison["result_label"] = comparison["actual"].map(OUTCOME_LABELS)
    comparison["predicted_label"] = comparison["predicted"].map(OUTCOME_LABELS)
    comparison["correct"] = comparison["actual"] == comparison["predicted"]
    comparison["status"] = comparison["correct"].map({True: "Correct", False: "Wrong"})

    st.dataframe(
        comparison[["date", "home_team", "away_team", "result_label", "predicted_label", "status"]]
        .rename(columns={
            "date": "Date", "home_team": "Home", "away_team": "Away",
            "result_label": "Actual Result", "predicted_label": "Predicted", "status": "Status",
        })
        .head(20),
        use_container_width=True,
        hide_index=True,
    )

    correct_preds = comparison["correct"].sum()
    total_preds = len(comparison)
    st.info(f"**Summary:** {correct_preds} correct predictions out of {total_preds} total ({correct_preds / total_preds:.1%})")

    st.markdown("---")
    st.subheader("Accuracy Over Time")

    comparison_sorted = comparison.sort_values("date")
    comparison_sorted["rolling_accuracy"] = (
        comparison_sorted["correct"].rolling(window=10, min_periods=1).mean() * 100
    )

    fig = px.line(
        comparison_sorted, x="date", y="rolling_accuracy",
        title="Rolling Accuracy (10-match window)",
        labels={"rolling_accuracy": "Accuracy (%)", "date": "Date"},
    )
    fig.update_layout(height=350)
    fig.add_hline(
        y=rf_metrics["accuracy"] * 100, line_dash="dash", line_color="red",
        annotation_text=f"Overall: {rf_metrics['accuracy']:.1%}",
    )
    st.plotly_chart(fig, use_container_width=True)

    st.markdown("---")
    st.subheader("Key Insights")

    col1, col2 = st.columns(2)
    with col1:
        st.markdown("**Strengths:**")
        if rf_metrics["accuracy"] > home_win_baseline:
            st.success(f"Beats the always-predict-home-win baseline ({home_win_baseline:.1%})")
        if rf_metrics["f1_score"] > 0.45:
            st.success("Reasonable weighted F1-score given three-way outcome prediction is a hard problem")

    with col2:
        st.markdown("**Areas for Improvement:**")
        st.warning("Draws are the hardest outcome to predict — see confusion matrix above")
        if rf_metrics["accuracy"] < 0.7:
            st.info("Accuracy has headroom; match outcomes have inherent randomness that limits achievable accuracy")
